# Generated by Django 6.0.1 on 2026-01-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BudgetApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Withdraw_Savings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("amount", models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="savings",
            name="surplus_money",
        ),
    ]
